### ISSUE TITLE
Magnetos off?

### ISSUE THREAD

**Issue by svm420** [camlost2/AJE#32] opened 2015-07-19 04:42 UTC
I am unable to start an engine from the KAX pack. It is the larger of the first 2 props. On the runway after staging to start the engine, it never starts and says flame out magnetos off. not sure what that mean or how to solve it. So this may not be a real issue, but I wanted some help with what that meant. Thanks!

**Comment by blowfishpro** [comment] 2015-07-23 01:51
Recent changes might fix this.  Could you try again?

**Comment by svm420** [comment] 2015-07-23 04:00
Just tried with the latest version of both AJE and SEngines. Still having the flameout with cause magnetos off. The double wasp engines will not even start. They flameout as soon as staged on the runway with the same cause listed. Maybe related? Let me know how I can help. :)

**Comment by ferram4** [comment] 2015-08-17 04:27
I've looked into this, and it seems to be connected to the engine sim being unable to produce > 0 power.  Modifying the configs to remove CoolerMin (I assume, setting the minimum temperature lower and so allowing it to produce power more easily?) allowed the engine to run, but resulted in the engine flaming out permanently in the same state if the throttle was dropped below ~85%.  Flameout occurred as brake shaft horsepower hit 0 and then engine couldn't be restarted from there.

**Comment by ferram4** [comment] 2015-08-25 17:48
I believe that this issue is fixed by #36, although I didn't add any code specifically for it.  I have been unable to reproduce the issue since correcting the boost pressure for the engines.

**Comment by blowfishpro** [comment] 2015-08-26 07:45
Yup.  Appears to be fixed.

**Closed as completed by blowfishpro** 2015-08-26 07:45 UTC
Labels: bug
